version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:13

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Linting and Formatting
          command: npm run lint

      - run:
          name: Unit Tests
          command: npm test

      - run:
          name: Print Docker version
          command: docker --version

      - run:
          name: Build and tag Docker images
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
            docker tag udagram-api-feed trangocquy123/udagram-api-feed:v1
            docker tag udagram-api-user trangocquy123/udagram-api-user:v1
            docker tag reverseproxy trangocquy123/reverseproxy:v1
            docker tag udagram-frontend:local trangocquy123/udagram-frontend:v1

      - run:
          name: Push Docker images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push trangocquy123/udagram-api-feed:v1
            docker push trangocquy123/udagram-api-user:v1
            docker push trangocquy123/reverseproxy:v1
            docker push trangocquy123/udagram-frontend:v1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
