# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'

version: 2.1




# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.

# See: https://circleci.com/docs/orb-intro/

orbs:

  docker: circleci/docker@2.2.0

# See: https://circleci.com/docs/configuration-reference/#workflows





jobs:

  build-and-push:

    executor: docker/docker

    steps:

      - checkout

      - setup_remote_docker

      - run:

          name: Build docker image

          command: |

            docker-compose -f docker-compose-build.yaml build --parallel

            docker tag udagram-api-feed duyhn6/udagram-api-feed:lastest

            docker tag udagram-api-user duyhn6/udagram-api-user:lastest

            docker tag reverseproxy duyhn6/reverseproxy:lastest

            docker tag udagram-frontend:local duyhn6/udagram-frontend:lastest

      - run:

          name: Publish Docker Image to Docker Hub

          command: |

            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            docker push duyhn6/udagram-api-feed:lastest

            docker push duyhn6/udagram-api-user:lastest

            docker push duyhn6/reverseproxy:lastest

            docker push duyhn6/udagram-frontend:lastest

workflows:

  default:

    jobs:

      - build-and-push